const gameData = {
    "list1": {
        "name": "Level 1: Green Grass",
        "points": 10,
        "bonusPoints": 5,
        "words": [
            { "id": 1, "word": "the", "sentences": [{ "text": "I see ___ sun.", "correct": true }, { "text": "I see ___ go.", "correct": false }, { "text": "I see ___ and.", "correct": false }] },
            { "id": 2, "word": "for", "sentences": [{ "text": "This is ___ you.", "correct": true }, { "text": "This is ___ up.", "correct": false }, { "text": "This is ___ am.", "correct": false }] },
            { "id": 3, "word": "I", "sentences": [{ "text": "___ am happy.", "correct": true }, { "text": "___ is happy.", "correct": false }, { "text": "___ are happy.", "correct": false }] },
            { "id": 4, "word": "to", "sentences": [{ "text": "Go ___ sleep.", "correct": true }, { "text": "I ___ six.", "correct": false }, { "text": "A ___ apple.", "correct": false }] },
            { "id": 5, "word": "was", "sentences": [{ "text": "It ___ cold.", "correct": true }, { "text": "It ___ is.", "correct": false }, { "text": "It ___ have.", "correct": false }] },
            { "id": 6, "word": "you", "sentences": [{ "text": "How are ___?", "correct": true }, { "text": "How are ___ me?", "correct": false }, { "text": "How are ___ today?", "correct": false }] },
            { "id": 7, "word": "said", "sentences": [{ "text": "He ___ hello.", "correct": true }, { "text": "He ___ say.", "correct": false }, { "text": "He ___ talking.", "correct": false }] },
            { "id": 8, "word": "it", "sentences": [{ "text": "Give ___ to me.", "correct": true }, { "text": "Give ___ my.", "correct": false }, { "text": "Give ___ and.", "correct": false }] },
            { "id": 9, "word": "on", "sentences": [{ "text": "Sit ___ the chair.", "correct": true }, { "text": "Sit ___ in.", "correct": false }, { "text": "Sit ___ floor.", "correct": false }] },
            { "id": 10, "word": "his", "sentences": [{ "text": "That is ___ hat.", "correct": true }, { "text": "That is ___ her.", "correct": false }, { "text": "That is ___ she.", "correct": false }] },
            { "id": 11, "word": "and", "sentences": [{ "text": "Mom ___ Dad.", "correct": true }, { "text": "I ___ happy.", "correct": false }, { "text": "Up ___ down.", "correct": false }] },
            { "id": 12, "word": "they", "sentences": [{ "text": "___ are playing.", "correct": true }, { "text": "___ is playing.", "correct": false }, { "text": "___ am playing.", "correct": false }] },
            { "id": 13, "word": "he", "sentences": [{ "text": "___ is a boy.", "correct": true }, { "text": "___ is a girl.", "correct": false }, { "text": "___ are happy.", "correct": false }] },
            { "id": 14, "word": "but", "sentences": [{ "text": "Small ___ fast.", "correct": true }, { "text": "Small ___ and.", "correct": false }, { "text": "Small ___ so.", "correct": false }] },
            { "id": 15, "word": "of", "sentences": [{ "text": "A bag ___ chips.", "correct": true }, { "text": "Go ___ bed.", "correct": false }, { "text": "I am ___ school.", "correct": false }] },
            { "id": 16, "word": "and", "sentences": [{ "text": "Red ___ blue.", "correct": true }, { "text": "Red ___ was.", "correct": false }, { "text": "Red ___ is.", "correct": false }] },
            { "id": 17, "word": "that", "sentences": [{ "text": "Look at ___.", "correct": true }, { "text": "Look at ___ me.", "correct": false }, { "text": "Look at ___ blue.", "correct": false }] },
            { "id": 18, "word": "in", "sentences": [{ "text": "It is ___ the box.", "correct": true }, { "text": "It is ___ table.", "correct": false }, { "text": "It is ___ sky.", "correct": false }] },
            { "id": 19, "word": "she", "sentences": [{ "text": "___ is a girl.", "correct": true }, { "text": "___ am a girl.", "correct": false }, { "text": "___ are a girl.", "correct": false }] },
            { "id": 20, "word": "look", "sentences": [{ "text": "___ at the cat.", "correct": true }, { "text": "___ to the cat.", "correct": false }, { "text": "___ for the cat.", "correct": false }] },
            { "id": 21, "word": "had", "sentences": [{ "text": "I ___ a snack.", "correct": true }, { "text": "I ___ have.", "correct": false }, { "text": "I ___ has.", "correct": false }] },
            { "id": 22, "word": "out", "sentences": [{ "text": "Get ___.", "correct": true }, { "text": "Get ___ in.", "correct": false }, { "text": "Get ___ up.", "correct": false }] },
            { "id": 23, "word": "at", "sentences": [{ "text": "Look ___ me.", "correct": true }, { "text": "Look ___ on.", "correct": false }, { "text": "Look ___ the.", "correct": false }] },
            { "id": 24, "word": "we", "sentences": [{ "text": "___ are friends.", "correct": true }, { "text": "___ is friends.", "correct": false }, { "text": "___ am friends.", "correct": false }] }
        ]
    },
"list2": {
        "name": "Level 2: Blue Sky",
        "points": 20,
        "bonusPoints": 10,
        "words": [
            { "id": 1, "word": "him", "sentences": [{ "text": "Give it to ___.", "correct": true }, { "text": "Give it to ___ he.", "correct": false }, { "text": "Give it to ___ his.", "correct": false }] },
            { "id": 2, "word": "am", "sentences": [{ "text": "I ___ seven.", "correct": true }, { "text": "I ___ is seven.", "correct": false }, { "text": "I ___ are seven.", "correct": false }] },
            { "id": 3, "word": "is", "sentences": [{ "text": "The sun ___ hot.", "correct": true }, { "text": "The sun ___ am hot.", "correct": false }, { "text": "The sun ___ are hot.", "correct": false }] },
            { "id": 4, "word": "with", "sentences": [{ "text": "Play ___ me.", "correct": true }, { "text": "Play ___ at me.", "correct": false }, { "text": "Play ___ was me.", "correct": false }] },
            { "id": 5, "word": "as", "sentences": [{ "text": "Big ___ a bus.", "correct": true }, { "text": "Big ___ is a bus.", "correct": false }, { "text": "Big ___ to a bus.", "correct": false }] },
            { "id": 6, "word": "her", "sentences": [{ "text": "This is ___ bag.", "correct": true }, { "text": "This is ___ she bag.", "correct": false }, { "text": "This is ___ him bag.", "correct": false }] },
            { "id": 7, "word": "be", "sentences": [{ "text": "I will ___ good.", "correct": true }, { "text": "I will ___ am good.", "correct": false }, { "text": "I will ___ are good.", "correct": false }] },
            { "id": 8, "word": "there", "sentences": [{ "text": "Look over ___.", "correct": true }, { "text": "Look over ___ they.", "correct": false }, { "text": "Look over ___ their.", "correct": false }] },
            { "id": 9, "word": "then", "sentences": [{ "text": "Eat, ___ play.", "correct": true }, { "text": "Eat, ___ than play.", "correct": false }, { "text": "Eat, ___ that play.", "correct": false }] },
            { "id": 10, "word": "have", "sentences": [{ "text": "I ___ a ball.", "correct": true }, { "text": "I ___ has a ball.", "correct": false }, { "text": "I ___ is a ball.", "correct": false }] },
            { "id": 11, "word": "up", "sentences": [{ "text": "Look ___ high.", "correct": true }, { "text": "Look ___ down high.", "correct": false }, { "text": "Look ___ in high.", "correct": false }] },
            { "id": 12, "word": "little", "sentences": [{ "text": "A ___ bug.", "correct": true }, { "text": "A ___ big bug.", "correct": false }, { "text": "A ___ red bug.", "correct": false }] },
            { "id": 13, "word": "all", "sentences": [{ "text": "Eat ___ of it.", "correct": true }, { "text": "Eat ___ for of it.", "correct": false }, { "text": "Eat ___ in of it.", "correct": false }] },
            { "id": 14, "word": "down", "sentences": [{ "text": "Sit ___ now.", "correct": true }, { "text": "Sit ___ up now.", "correct": false }, { "text": "Sit ___ on now.", "correct": false }] },
            { "id": 15, "word": "some", "sentences": [{ "text": "I want ___ milk.", "correct": true }, { "text": "I want ___ any milk.", "correct": false }, { "text": "I want ___ of milk.", "correct": false }] },
            { "id": 16, "word": "do", "sentences": [{ "text": "___ you like it?", "correct": true }, { "text": "___ does you like it?", "correct": false }, { "text": "___ doing you like it?", "correct": false }] },
            { "id": 17, "word": "go", "sentences": [{ "text": "Let's ___ out.", "correct": true }, { "text": "Let's ___ going out.", "correct": false }, { "text": "Let's ___ goes out.", "correct": false }] },
            { "id": 18, "word": "what", "sentences": [{ "text": "___ is that?", "correct": true }, { "text": "___ am that?", "correct": false }, { "text": "___ are that?", "correct": false }] },
            { "id": 19, "word": "get", "sentences": [{ "text": "Go ___ the ball.", "correct": true }, { "text": "Go ___ got the ball.", "correct": false }, { "text": "Go ___ gets the ball.", "correct": false }] },
            { "id": 20, "word": "some", "sentences": [{ "text": "Here is ___ cake.", "correct": true }, { "text": "Here is ___ any cake.", "correct": false }, { "text": "Here is ___ much cake.", "correct": false }] },
            { "id": 21, "word": "my", "sentences": [{ "text": "This is ___ cat.", "correct": true }, { "text": "This is ___ me cat.", "correct": false }, { "text": "This is ___ I cat.", "correct": false }] },
            { "id": 22, "word": "them", "sentences": [{ "text": "See ___ run.", "correct": true }, { "text": "See ___ they run.", "correct": false }, { "text": "See ___ their run.", "correct": false }] },
            { "id": 23, "word": "can", "sentences": [{ "text": "I ___ jump.", "correct": true }, { "text": "I ___ am jump.", "correct": false }, { "text": "I ___ is jump.", "correct": false }] },
            { "id": 24, "word": "would", "sentences": [{ "text": "___ you like one?", "correct": true }, { "text": "___ wood you like one?", "correct": false }, { "text": "___ will you like one?", "correct": false }] }
        ]
    },
"list3": {
        "name": "Level 3: Bright Sun",
        "points": 30,
        "bonusPoints": 15,
        "words": [
            { "id": 1, "word": "could", "sentences": [{ "text": "I ___ run fast.", "correct": true }, { "text": "I ___ can run fast.", "correct": false }, { "text": "I ___ will run fast.", "correct": false }] },
            { "id": 2, "word": "me", "sentences": [{ "text": "Look at ___.", "correct": true }, { "text": "Look at ___ I.", "correct": false }, { "text": "Look at ___ my.", "correct": false }] },
            { "id": 3, "word": "see", "sentences": [{ "text": "I ___ a star.", "correct": true }, { "text": "I ___ sea a star.", "correct": false }, { "text": "I ___ seen a star.", "correct": false }] },
            { "id": 4, "word": "when", "sentences": [{ "text": "___ can we go?", "correct": true }, { "text": "___ is we go?", "correct": false }, { "text": "___ am we go?", "correct": false }] },
            { "id": 5, "word": "like", "sentences": [{ "text": "I ___ cake.", "correct": true }, { "text": "I ___ as cake.", "correct": false }, { "text": "I ___ am cake.", "correct": false }] },
            { "id": 6, "word": "not", "sentences": [{ "text": "I am ___ sad.", "correct": true }, { "text": "I am ___ no.", "correct": false }, { "text": "I am ___ is.", "correct": false }] },
            { "id": 7, "word": "one", "sentences": [{ "text": "I have ___ dog.", "correct": true }, { "text": "I have ___ won dog.", "correct": false }, { "text": "I have ___ on dog.", "correct": false }] },
            { "id": 8, "word": "were", "sentences": [{ "text": "They ___ happy.", "correct": true }, { "text": "They ___ was happy.", "correct": false }, { "text": "They ___ is happy.", "correct": false }] },
            { "id": 9, "word": "will", "sentences": [{ "text": "I ___ help.", "correct": true }, { "text": "I ___ am help.", "correct": false }, { "text": "I ___ is help.", "correct": false }] },
            { "id": 10, "word": "this", "sentences": [{ "text": "___ is my toy.", "correct": true }, { "text": "___ that is my toy.", "correct": false }, { "text": "___ the is my toy.", "correct": false }] },
            { "id": 11, "word": "did", "sentences": [{ "text": "___ you win?", "correct": true }, { "text": "___ do you win?", "correct": false }, { "text": "___ does you win?", "correct": false }] },
            { "id": 12, "word": "yes", "sentences": [{ "text": "___, please.", "correct": true }, { "text": "___, no please.", "correct": false }, { "text": "___, and please.", "correct": false }] },
            { "id": 13, "word": "big", "sentences": [{ "text": "A ___ boat.", "correct": true }, { "text": "A ___ little boat.", "correct": false }, { "text": "A ___ red boat.", "correct": false }] },
            { "id": 14, "word": "ride", "sentences": [{ "text": "___ the bike.", "correct": true }, { "text": "___ road the bike.", "correct": false }, { "text": "___ red the bike.", "correct": false }] },
            { "id": 15, "word": "now", "sentences": [{ "text": "Do it ___.", "correct": true }, { "text": "Do it ___ no.", "correct": false }, { "text": "Do it ___ know.", "correct": false }] },
            { "id": 16, "word": "went", "sentences": [{ "text": "He ___ home.", "correct": true }, { "text": "He ___ go home.", "correct": false }, { "text": "He ___ goes home.", "correct": false }] },
            { "id": 17, "word": "very", "sentences": [{ "text": "I am ___ cold.", "correct": true }, { "text": "I am ___ every cold.", "correct": false }, { "text": "I am ___ vary cold.", "correct": false }] },
            { "id": 18, "word": "long", "sentences": [{ "text": "A ___ snake.", "correct": true }, { "text": "A ___ tall snake.", "correct": false }, { "text": "A ___ short snake.", "correct": false }] },
            { "id": 19, "word": "an", "sentences": [{ "text": "Eat ___ egg.", "correct": true }, { "text": "Eat ___ a egg.", "correct": false }, { "text": "Eat ___ the egg.", "correct": false }] },
            { "id": 20, "word": "no", "sentences": [{ "text": "___, thank you.", "correct": true }, { "text": "___ know, thank you.", "correct": false }, { "text": "___ not, thank you.", "correct": false }] },
            { "id": 21, "word": "into", "sentences": [{ "text": "Jump ___ it.", "correct": true }, { "text": "Jump ___ to it.", "correct": false }, { "text": "Jump ___ in it.", "correct": false }] },
            { "id": 22, "word": "over", "sentences": [{ "text": "Jump ___ it.", "correct": true }, { "text": "Jump ___ under it.", "correct": false }, { "text": "Jump ___ on it.", "correct": false }] },
            { "id": 23, "word": "are", "sentences": [{ "text": "We ___ sad.", "correct": true }, { "text": "We ___ am sad.", "correct": false }, { "text": "We ___ is sad.", "correct": false }] },
            { "id": 24, "word": "just", "sentences": [{ "text": "___ one.", "correct": true }, { "text": "___ only one.", "correct": false }, { "text": "___ alone one.", "correct": false }] }
        ]
    },
"list4": {
        "name": "Level 4: Purple Mountain",
        "points": 40,
        "bonusPoints": 20,
        "words": [
            { "id": 1, "word": "come", "sentences": [{ "text": "___ here.", "correct": true }, { "text": "___ came here.", "correct": false }, { "text": "___ go here.", "correct": false }] },
            { "id": 2, "word": "blue", "sentences": [{ "text": "The sky is ___.", "correct": true }, { "text": "The sky is ___ red.", "correct": false }, { "text": "The sky is ___ blow.", "correct": false }] },
            { "id": 3, "word": "came", "sentences": [{ "text": "He ___ over.", "correct": true }, { "text": "He ___ come over.", "correct": false }, { "text": "He ___ coming over.", "correct": false }] },
            { "id": 4, "word": "if", "sentences": [{ "text": "___ it rains, stay.", "correct": true }, { "text": "___ is it rains.", "correct": false }, { "text": "___ and it rains.", "correct": false }] },
            { "id": 5, "word": "your", "sentences": [{ "text": "Is this ___?", "correct": true }, { "text": "Is this ___ you?", "correct": false }, { "text": "Is this ___ you're?", "correct": false }] },
            { "id": 6, "word": "ask", "sentences": [{ "text": "___ a question.", "correct": true }, { "text": "___ asked a question.", "correct": false }, { "text": "___ telling a question.", "correct": false }] },
            { "id": 7, "word": "its", "sentences": [{ "text": "The dog ate ___ food.", "correct": true }, { "text": "The dog ate ___ it's food.", "correct": false }, { "text": "The dog ate ___ is food.", "correct": false }] },
            { "id": 8, "word": "want", "sentences": [{ "text": "I ___ cake.", "correct": true }, { "text": "I ___ wants cake.", "correct": false }, { "text": "I ___ wanting cake.", "correct": false }] },
            { "id": 9, "word": "red", "sentences": [{ "text": "An apple is ___.", "correct": true }, { "text": "An apple is ___ blue.", "correct": false }, { "text": "An apple is ___ read.", "correct": false }] },
            { "id": 10, "word": "put", "sentences": [{ "text": "___ it away.", "correct": true }, { "text": "___ putting it away.", "correct": false }, { "text": "___ puts it away.", "correct": false }] },
            { "id": 11, "word": "from", "sentences": [{ "text": "This is ___ me.", "correct": true }, { "text": "This is ___ to me.", "correct": false }, { "text": "This is ___ for me.", "correct": false }] },
            { "id": 12, "word": "every", "sentences": [{ "text": "___ day I play.", "correct": true }, { "text": "___ very day I play.", "correct": false }, { "text": "___ all day I play.", "correct": false }] },
            { "id": 13, "word": "good", "sentences": [{ "text": "Have a ___ day.", "correct": true }, { "text": "Have a ___ well day.", "correct": false }, { "text": "Have a ___ best day.", "correct": false }] },
            { "id": 14, "word": "pretty", "sentences": [{ "text": "A ___ flower.", "correct": true }, { "text": "A ___ ugly flower.", "correct": false }, { "text": "A ___ and flower.", "correct": false }] },
            { "id": 15, "word": "don't", "sentences": [{ "text": "___ run!", "correct": true }, { "text": "___ do not run!", "correct": false }, { "text": "___ doesn't run!", "correct": false }] },
            { "id": 16, "word": "any", "sentences": [{ "text": "Do you have ___?", "correct": true }, { "text": "Do you have ___ some?", "correct": false }, { "text": "Do you have ___ many?", "correct": false }] },
            { "id": 17, "word": "too", "sentences": [{ "text": "I want one ___.", "correct": true }, { "text": "I want one ___ to.", "correct": false }, { "text": "I want one ___ two.", "correct": false }] },
            { "id": 18, "word": "how", "sentences": [{ "text": "___ are you?", "correct": true }, { "text": "___ is you?", "correct": false }, { "text": "___ am you?", "correct": false }] },
            { "id": 19, "word": "got", "sentences": [{ "text": "I ___ a prize.", "correct": true }, { "text": "I ___ get a prize.", "correct": false }, { "text": "I ___ getting a prize.", "correct": false }] },
            { "id": 20, "word": "know", "sentences": [{ "text": "I ___ the way.", "correct": true }, { "text": "I ___ no the way.", "correct": false }, { "text": "I ___ now the way.", "correct": false }] },
            { "id": 21, "word": "jump", "sentences": [{ "text": "___ over it.", "correct": true }, { "text": "___ jumping over it.", "correct": false }, { "text": "___ jumped over it.", "correct": false }] },
            { "id": 22, "word": "take", "sentences": [{ "text": "___ a cookie.", "correct": true }, { "text": "___ took a cookie.", "correct": false }, { "text": "___ taking a cookie.", "correct": false }] },
            { "id": 23, "word": "about", "sentences": [{ "text": "Tell me ___ it.", "correct": true }, { "text": "Tell me ___ was it.", "correct": false }, { "text": "Tell me ___ is it.", "correct": false }] },
            { "id": 24, "word": "green", "sentences": [{ "text": "The grass is ___.", "correct": true }, { "text": "The grass is ___ blue.", "correct": false }, { "text": "The grass is ___ red.", "correct": false }] }
        ]
    },
"list5": {
        "name": "Level 5: Silver River",
        "points": 50,
        "bonusPoints": 25,
        "words": [
            { "id": 1, "word": "around", "sentences": [{ "text": "Run ___ the tree.", "correct": true }, { "text": "Run ___ about the tree.", "correct": false }, { "text": "Run ___ is the tree.", "correct": false }] },
            { "id": 2, "word": "four", "sentences": [{ "text": "I have ___ toys.", "correct": true }, { "text": "I have ___ for toys.", "correct": false }, { "text": "I have ___ fire toys.", "correct": false }] },
            { "id": 3, "word": "right", "sentences": [{ "text": "Turn ___ here.", "correct": true }, { "text": "Turn ___ write here.", "correct": false }, { "text": "Turn ___ white here.", "correct": false }] },
            { "id": 4, "word": "away", "sentences": [{ "text": "Go ___!", "correct": true }, { "text": "Go ___ always!", "correct": false }, { "text": "Go ___ way!", "correct": false }] },
            { "id": 5, "word": "where", "sentences": [{ "text": "___ is it?", "correct": true }, { "text": "___ were is it?", "correct": false }, { "text": "___ wear is it.", "correct": false }] },
            { "id": 6, "word": "saw", "sentences": [{ "text": "I ___ a bird.", "correct": true }, { "text": "I ___ see a bird.", "correct": false }, { "text": "I ___ was a bird.", "correct": false }] },
            { "id": 7, "word": "ran", "sentences": [{ "text": "The cat ___ away.", "correct": true }, { "text": "The cat ___ run away.", "correct": false }, { "text": "The cat ___ rain away.", "correct": false }] },
            { "id": 8, "word": "call", "sentences": [{ "text": "Please ___ me.", "correct": true }, { "text": "Please ___ cold me.", "correct": false }, { "text": "Please ___ came me.", "correct": false }] },
            { "id": 9, "word": "sleep", "sentences": [{ "text": "Go to ___.", "correct": true }, { "text": "Go to ___ sheep.", "correct": false }, { "text": "Go to ___ step.", "correct": false }] },
            { "id": 10, "word": "let", "sentences": [{ "text": "___ us go.", "correct": true }, { "text": "___ let's us go.", "correct": false }, { "text": "___ late us go.", "correct": false }] },
            { "id": 11, "word": "old", "sentences": [{ "text": "An ___ book.", "correct": true }, { "text": "An ___ cold book.", "correct": false }, { "text": "An ___ and book.", "correct": false }] },
            { "id": 12, "word": "brown", "sentences": [{ "text": "A ___ dog.", "correct": true }, { "text": "A ___ down dog.", "correct": false }, { "text": "A ___ blue dog.", "correct": false }] },
            { "id": 13, "word": "by", "sentences": [{ "text": "Sit ___ me.", "correct": true }, { "text": "Sit ___ buy me.", "correct": false }, { "text": "Sit ___ bye me.", "correct": false }] },
            { "id": 14, "word": "yellow", "sentences": [{ "text": "A ___ sun.", "correct": true }, { "text": "A ___ blue sun.", "correct": false }, { "text": "A ___ hello sun.", "correct": false }] },
            { "id": 15, "word": "after", "sentences": [{ "text": "___ school, we play.", "correct": true }, { "text": "___ always school.", "correct": false }, { "text": "___ about school.", "correct": false }] },
            { "id": 16, "word": "their", "sentences": [{ "text": "It is ___ house.", "correct": true }, { "text": "It is ___ there house.", "correct": false }, { "text": "It is ___ they're house.", "correct": false }] },
            { "id": 17, "word": "help", "sentences": [{ "text": "Can you ___?", "correct": true }, { "text": "Can you ___ helps?", "correct": false }, { "text": "Can you ___ helping?", "correct": false }] },
            { "id": 18, "word": "well", "sentences": [{ "text": "I feel ___.", "correct": true }, { "text": "I feel ___ will.", "correct": false }, { "text": "I feel ___ wall.", "correct": false }] },
            { "id": 19, "word": "make", "sentences": [{ "text": "I can ___ it.", "correct": true }, { "text": "I can ___ made it.", "correct": false }, { "text": "I can ___ makes it.", "correct": false }] },
            { "id": 20, "word": "think", "sentences": [{ "text": "I ___ so.", "correct": true }, { "text": "I ___ thing so.", "correct": false }, { "text": "I ___ thank so.", "correct": false }] },
            { "id": 21, "word": "five", "sentences": [{ "text": "I have ___ pens.", "correct": true }, { "text": "I have ___ fine pens.", "correct": false }, { "text": "I have ___ fire pens.", "correct": false }] },
            { "id": 22, "word": "going", "sentences": [{ "text": "I am ___ home.", "correct": true }, { "text": "I am ___ go home.", "correct": false }, { "text": "I am ___ goes home.", "correct": false }] },
            { "id": 23, "word": "here", "sentences": [{ "text": "Come ___.", "correct": true }, { "text": "Come ___ hear.", "correct": false }, { "text": "Come ___ her.", "correct": false }] },
            { "id": 24, "word": "six", "sentences": [{ "text": "I am ___ years old.", "correct": true }, { "text": "I am ___ sick years old.", "correct": false }, { "text": "I am ___ sun years old.", "correct": false }] }
        ]
    },
"list6": {
        "name": "Level 6: Golden Road",
        "points": 60,
        "bonusPoints": 30,
        "words": [
            { "id": 1, "word": "walk", "sentences": [{ "text": "___ to school.", "correct": true }, { "text": "___ woke to school.", "correct": false }, { "text": "___ work to school.", "correct": false }] },
            { "id": 2, "word": "cold", "sentences": [{ "text": "It is ___ today.", "correct": true }, { "text": "It is ___ gold today.", "correct": false }, { "text": "It is ___ called today.", "correct": false }] },
            { "id": 3, "word": "again", "sentences": [{ "text": "Do it ___.", "correct": true }, { "text": "Do it ___ against.", "correct": false }, { "text": "Do it ___ and.", "correct": false }] },
            { "id": 4, "word": "two", "sentences": [{ "text": "I have ___ ears.", "correct": true }, { "text": "I have ___ too ears.", "correct": false }, { "text": "I have ___ to ears.", "correct": false }] },
            { "id": 5, "word": "stop", "sentences": [{ "text": "___ the car.", "correct": true }, { "text": "___ step the car.", "correct": false }, { "text": "___ shop the car.", "correct": false }] },
            { "id": 6, "word": "play", "sentences": [{ "text": "Go ___ outside.", "correct": true }, { "text": "Go ___ pray outside.", "correct": false }, { "text": "Go ___ pay outside.", "correct": false }] },
            { "id": 7, "word": "off", "sentences": [{ "text": "Turn it ___.", "correct": true }, { "text": "Turn it ___ on.", "correct": false }, { "text": "Turn it ___ of.", "correct": false }] },
            { "id": 8, "word": "who", "sentences": [{ "text": "___ is that?", "correct": true }, { "text": "___ how is that?", "correct": false }, { "text": "___ why is that?", "correct": false }] },
            { "id": 9, "word": "today", "sentences": [{ "text": "It is hot ___.", "correct": true }, { "text": "It is hot ___ yesterday.", "correct": false }, { "text": "It is hot ___ to.", "correct": false }] },
            { "id": 10, "word": "never", "sentences": [{ "text": "I ___ cry.", "correct": true }, { "text": "I ___ ever cry.", "correct": false }, { "text": "I ___ near cry.", "correct": false }] },
            { "id": 11, "word": "or", "sentences": [{ "text": "Red ___ blue?", "correct": true }, { "text": "Red ___ of blue?", "correct": false }, { "text": "Red ___ on blue?", "correct": false }] },
            { "id": 12, "word": "fly", "sentences": [{ "text": "Birds can ___.", "correct": true }, { "text": "Birds can ___ fry.", "correct": false }, { "text": "Birds can ___ flag.", "correct": false }] },
            { "id": 13, "word": "before", "sentences": [{ "text": "Eat ___ bed.", "correct": true }, { "text": "Eat ___ after bed.", "correct": false }, { "text": "Eat ___ because bed.", "correct": false }] },
            { "id": 14, "word": "myself", "sentences": [{ "text": "I did it ___.", "correct": true }, { "text": "I did it ___ me.", "correct": false }, { "text": "I did it ___ my.", "correct": false }] },
            { "id": 15, "word": "been", "sentences": [{ "text": "Where have you ___?", "correct": true }, { "text": "Where have you ___ bin?", "correct": false }, { "text": "Where have you ___ being?", "correct": false }] },
            { "id": 16, "word": "eat", "sentences": [{ "text": "___ your apple.", "correct": true }, { "text": "___ ate your apple.", "correct": false }, { "text": "___ each your apple.", "correct": false }] },
            { "id": 17, "word": "seven", "sentences": [{ "text": "I see ___ birds.", "correct": true }, { "text": "I see ___ seventeen birds.", "correct": false }, { "text": "I see ___ sun birds.", "correct": false }] },
            { "id": 18, "word": "may", "sentences": [{ "text": "___ I go out?", "correct": true }, { "text": "___ My I go out?", "correct": false }, { "text": "___ Me I go out?", "correct": false }] },
            { "id": 19, "word": "eight", "sentences": [{ "text": "I am ___.", "correct": true }, { "text": "I am ___ ate.", "correct": false }, { "text": "I am ___ egg.", "correct": false }] },
            { "id": 20, "word": "first", "sentences": [{ "text": "I am ___.", "correct": true }, { "text": "I am ___ fast.", "correct": false }, { "text": "I am ___ find.", "correct": false }] },
            { "id": 21, "word": "round", "sentences": [{ "text": "A ___ ball.", "correct": true }, { "text": "A ___ around ball.", "correct": false }, { "text": "A ___ red ball.", "correct": false }] },
            { "id": 22, "word": "black", "sentences": [{ "text": "A ___ cat.", "correct": true }, { "text": "A ___ back cat.", "correct": false }, { "text": "A ___ blue cat.", "correct": false }] },
            { "id": 23, "word": "tell", "sentences": [{ "text": "___ me.", "correct": true }, { "text": "___ tall me.", "correct": false }, { "text": "___ till me.", "correct": false }] },
            { "id": 24, "word": "goes", "sentences": [{ "text": "The bus ___.", "correct": true }, { "text": "The bus ___ go.", "correct": false }, { "text": "The bus ___ going.", "correct": false }] }
        ]
    },
"list7": {
        "name": "Level 7: Orange Sunset",
        "points": 70,
        "bonusPoints": 35,
        "words": [
            { "id": 1, "word": "much", "sentences": [{ "text": "How ___ is it?", "correct": true }, { "text": "How ___ many is it?", "correct": false }, { "text": "How ___ must is it?", "correct": false }] },
            { "id": 2, "word": "write", "sentences": [{ "text": "___ your name.", "correct": true }, { "text": "___ right your name.", "correct": false }, { "text": "___ white your name.", "correct": false }] },
            { "id": 3, "word": "try", "sentences": [{ "text": "___ to jump.", "correct": true }, { "text": "___ tray to jump.", "correct": false }, { "text": "___ tiny to jump.", "correct": false }] },
            { "id": 4, "word": "keep", "sentences": [{ "text": "___ it safe.", "correct": true }, { "text": "___ sleep it safe.", "correct": false }, { "text": "___ deep it safe.", "correct": false }] },
            { "id": 5, "word": "white", "sentences": [{ "text": "A ___ cloud.", "correct": true }, { "text": "A ___ write cloud.", "correct": false }, { "text": "A ___ what cloud.", "correct": false }] },
            { "id": 6, "word": "new", "sentences": [{ "text": "I like your ___ hat.", "correct": true }, { "text": "I like your ___ now hat.", "correct": false }, { "text": "I like your ___ knew hat.", "correct": false }] },
            { "id": 7, "word": "ten", "sentences": [{ "text": "I have ___ fingers.", "correct": true }, { "text": "I have ___ then fingers.", "correct": false }, { "text": "I have ___ the fingers.", "correct": false }] },
            { "id": 8, "word": "must", "sentences": [{ "text": "I ___ go now.", "correct": true }, { "text": "I ___ much go now.", "correct": false }, { "text": "I ___ most go now.", "correct": false }] },
            { "id": 9, "word": "always", "sentences": [{ "text": "___ be kind.", "correct": true }, { "text": "___ away be kind.", "correct": false }, { "text": "___ also be kind.", "correct": false }] },
            { "id": 10, "word": "does", "sentences": [{ "text": "___ he like it?", "correct": true }, { "text": "___ do he like it?", "correct": false }, { "text": "___ doing he like it?", "correct": false }] },
            { "id": 11, "word": "give", "sentences": [{ "text": "___ me a hug.", "correct": true }, { "text": "___ gave me a hug.", "correct": false }, { "text": "___ goes me a hug.", "correct": false }] },
            { "id": 12, "word": "drink", "sentences": [{ "text": "___ some water.", "correct": true }, { "text": "___ drunk some water.", "correct": false }, { "text": "___ pink some water.", "correct": false }] },
            { "id": 13, "word": "work", "sentences": [{ "text": "Do your ___.", "correct": true }, { "text": "Do your ___ walk.", "correct": false }, { "text": "Do your ___ word.", "correct": false }] },
            { "id": 14, "word": "once", "sentences": [{ "text": "I went ___.", "correct": true }, { "text": "I went ___ one.", "correct": false }, { "text": "I went ___ only.", "correct": false }] },
            { "id": 15, "word": "start", "sentences": [{ "text": "___ the game.", "correct": true }, { "text": "___ stay the game.", "correct": false }, { "text": "___ stop the game.", "correct": false }] },
            { "id": 16, "word": "soon", "sentences": [{ "text": "See you ___.", "correct": true }, { "text": "See you ___ some.", "correct": false }, { "text": "See you ___ sun.", "correct": false }] },
            { "id": 17, "word": "bring", "sentences": [{ "text": "___ your book.", "correct": true }, { "text": "___ bright your book.", "correct": false }, { "text": "___ big your book.", "correct": false }] },
            { "id": 18, "word": "has", "sentences": [{ "text": "She ___ a dog.", "correct": true }, { "text": "She ___ have a dog.", "correct": false }, { "text": "She ___ is a dog.", "correct": false }] },
            { "id": 19, "word": "our", "sentences": [{ "text": "___ house is red.", "correct": true }, { "text": "___ are house is red.", "correct": false }, { "text": "___ out house is red.", "correct": false }] },
            { "id": 20, "word": "find", "sentences": [{ "text": "___ the toy.", "correct": true }, { "text": "___ fine the toy.", "correct": false }, { "text": "___ found the toy.", "correct": false }] },
            { "id": 21, "word": "warm", "sentences": [{ "text": "The sun is ___.", "correct": true }, { "text": "The sun is ___ worm.", "correct": false }, { "text": "The sun is ___ walk.", "correct": false }] },
            { "id": 22, "word": "better", "sentences": [{ "text": "I feel ___.", "correct": true }, { "text": "I feel ___ best.", "correct": false }, { "text": "I feel ___ butter.", "correct": false }] },
            { "id": 23, "word": "made", "sentences": [{ "text": "I ___ a cake.", "correct": true }, { "text": "I ___ make a cake.", "correct": false }, { "text": "I ___ mad a cake.", "correct": false }] },
            { "id": 24, "word": "ate", "sentences": [{ "text": "I ___ an apple.", "correct": true }, { "text": "I ___ eat an apple.", "correct": false }, { "text": "I ___ at an apple.", "correct": false }] }
        ]
    },
"list8": {
        "name": "Level 8: Pink Blossom",
        "points": 80,
        "bonusPoints": 40,
        "words": [
            { "id": 1, "word": "run", "sentences": [{ "text": "I can ___ fast.", "correct": true }, { "text": "I can ___ ran fast.", "correct": false }, { "text": "I can ___ sun fast.", "correct": false }] },
            { "id": 2, "word": "full", "sentences": [{ "text": "The cup is ___.", "correct": true }, { "text": "The cup is ___ fall.", "correct": false }, { "text": "The cup is ___ fill.", "correct": false }] },
            { "id": 3, "word": "only", "sentences": [{ "text": "I have ___ one.", "correct": true }, { "text": "I have ___ on one.", "correct": false }, { "text": "I have ___ open one.", "correct": false }] },
            { "id": 4, "word": "gave", "sentences": [{ "text": "He ___ it to me.", "correct": true }, { "text": "He ___ give it to me.", "correct": false }, { "text": "He ___ goes it to me.", "correct": false }] },
            { "id": 5, "word": "hold", "sentences": [{ "text": "___ my hand.", "correct": true }, { "text": "___ help my hand.", "correct": false }, { "text": "___ cold my hand.", "correct": false }] },
            { "id": 6, "word": "us", "sentences": [{ "text": "Play with ___.", "correct": true }, { "text": "Play with ___ use.", "correct": false }, { "text": "Play with ___ up.", "correct": false }] },
            { "id": 7, "word": "buy", "sentences": [{ "text": "___ a toy.", "correct": true }, { "text": "___ by a toy.", "correct": false }, { "text": "___ bye a toy.", "correct": false }] },
            { "id": 8, "word": "three", "sentences": [{ "text": "I see ___ cats.", "correct": true }, { "text": "I see ___ the cats.", "correct": false }, { "text": "I see ___ tree cats.", "correct": false }] },
            { "id": 9, "word": "those", "sentences": [{ "text": "Look at ___.", "correct": true }, { "text": "Look at ___ these.", "correct": false }, { "text": "Look at ___ this.", "correct": false }] },
            { "id": 10, "word": "funny", "sentences": [{ "text": "A ___ clown.", "correct": true }, { "text": "A ___ find clown.", "correct": false }, { "text": "A ___ sunny clown.", "correct": false }] },
            { "id": 11, "word": "open", "sentences": [{ "text": "___ the door.", "correct": true }, { "text": "___ only the door.", "correct": false }, { "text": "___ upon the door.", "correct": false }] },
            { "id": 12, "word": "done", "sentences": [{ "text": "I am ___.", "correct": true }, { "text": "I am ___ down.", "correct": false }, { "text": "I am ___ does.", "correct": false }] },
            { "id": 13, "word": "use", "sentences": [{ "text": "___ a pen.", "correct": true }, { "text": "___ us a pen.", "correct": false }, { "text": "___ used a pen.", "correct": false }] },
            { "id": 14, "word": "under", "sentences": [{ "text": "Sit ___ the tree.", "correct": true }, { "text": "Sit ___ upon the tree.", "correct": false }, { "text": "Sit ___ until the tree.", "correct": false }] },
            { "id": 15, "word": "hurt", "sentences": [{ "text": "Did you get ___?", "correct": true }, { "text": "Did you get ___ hat?", "correct": false }, { "text": "Did you get ___ hot?", "correct": false }] },
            { "id": 16, "word": "fast", "sentences": [{ "text": "Run ___!", "correct": true }, { "text": "Run ___ first!", "correct": false }, { "text": "Run ___ fat!", "correct": false }] },
            { "id": 17, "word": "sit", "sentences": [{ "text": "Please ___ down.", "correct": true }, { "text": "Please ___ sat down.", "correct": false }, { "text": "Please ___ six down.", "correct": false }] },
            { "id": 18, "word": "pull", "sentences": [{ "text": "___ the rope.", "correct": true }, { "text": "___ pull full the rope.", "correct": false }, { "text": "___ put the rope.", "correct": false }] },
            { "id": 19, "word": "which", "sentences": [{ "text": "___ one is it?", "correct": true }, { "text": "___ wish one is it?", "correct": false }, { "text": "___ what one is it?", "correct": false }] },
            { "id": 20, "word": "cut", "sentences": [{ "text": "___ the paper.", "correct": true }, { "text": "___ cat the paper.", "correct": false }, { "text": "___ can the paper.", "correct": false }] },
            { "id": 21, "word": "read", "sentences": [{ "text": "___ a book.", "correct": true }, { "text": "___ red a book.", "correct": false }, { "text": "___ ride a book.", "correct": false }] },
            { "id": 22, "word": "fall", "sentences": [{ "text": "Don't ___ down.", "correct": true }, { "text": "Don't ___ full down.", "correct": false }, { "text": "Don't ___ fill down.", "correct": false }] },
            { "id": 23, "word": "say", "sentences": [{ "text": "What did you ___?", "correct": true }, { "text": "What did you ___ said?", "correct": false }, { "text": "What did you ___ see?", "correct": false }] },
            { "id": 24, "word": "why", "sentences": [{ "text": "___ are you sad?", "correct": true }, { "text": "___ who are you sad?", "correct": false }, { "text": "___ way are you sad?", "correct": false }] }
        ]
    },
"list9": {
        "name": "Level 9: Crystal Cave",
        "points": 100,
        "bonusPoints": 50,
        "words": [
            { "id": 1, "word": "light", "sentences": [{ "text": "Turn on the ___.", "correct": true }, { "text": "Turn on the ___ like.", "correct": false }, { "text": "Turn on the ___ night.", "correct": false }] },
            { "id": 2, "word": "own", "sentences": [{ "text": "My ___ room.", "correct": true }, { "text": "My ___ one room.", "correct": false }, { "text": "My ___ on room.", "correct": false }] },
            { "id": 3, "word": "kind", "sentences": [{ "text": "Be ___ to all.", "correct": true }, { "text": "Be ___ king to all.", "correct": false }, { "text": "Be ___ find to all.", "correct": false }] },
            { "id": 4, "word": "pick", "sentences": [{ "text": "___ a flower.", "correct": true }, { "text": "___ pink a flower.", "correct": false }, { "text": "___ pack a flower.", "correct": false }] },
            { "id": 5, "word": "carry", "sentences": [{ "text": "___ the bag.", "correct": true }, { "text": "___ candy the bag.", "correct": false }, { "text": "___ hurry the bag.", "correct": false }] },
            { "id": 6, "word": "both", "sentences": [{ "text": "I like ___.", "correct": true }, { "text": "I like ___ boat.", "correct": false }, { "text": "I like ___ bath.", "correct": false }] },
            { "id": 7, "word": "small", "sentences": [{ "text": "A ___ ant.", "correct": true }, { "text": "A ___ ball ant.", "correct": false }, { "text": "A ___ smile ant.", "correct": false }] },
            { "id": 8, "word": "live", "sentences": [{ "text": "Where do you ___?", "correct": true }, { "text": "Where do you ___ like?", "correct": false }, { "text": "Where do you ___ life?", "correct": false }] },
            { "id": 9, "word": "found", "sentences": [{ "text": "I ___ my hat.", "correct": true }, { "text": "I ___ find my hat.", "correct": false }, { "text": "I ___ sound my hat.", "correct": false }] },
            { "id": 10, "word": "upon", "sentences": [{ "text": "Once ___ a time.", "correct": true }, { "text": "Once ___ up a time.", "correct": false }, { "text": "Once ___ open a time.", "correct": false }] },
            { "id": 11, "word": "wash", "sentences": [{ "text": "___ your hands.", "correct": true }, { "text": "___ wish your hands.", "correct": false }, { "text": "___ watch your hands.", "correct": false }] },
            { "id": 12, "word": "thank", "sentences": [{ "text": "___ you!", "correct": true }, { "text": "___ think you!", "correct": false }, { "text": "___ thing you!", "correct": false }] },
            { "id": 13, "word": "show", "sentences": [{ "text": "___ me the toy.", "correct": true }, { "text": "___ shoe me the toy.", "correct": false }, { "text": "___ saw me the toy.", "correct": false }] },
            { "id": 14, "word": "wish", "sentences": [{ "text": "Make a ___.", "correct": true }, { "text": "Make a ___ wash.", "correct": false }, { "text": "Make a ___ which.", "correct": false }] },
            { "id": 15, "word": "draw", "sentences": [{ "text": "___ a cat.", "correct": true }, { "text": "___ drawer a cat.", "correct": false }, { "text": "___ drink a cat.", "correct": false }] },
            { "id": 16, "word": "hot", "sentences": [{ "text": "The sun is ___.", "correct": true }, { "text": "The sun is ___ hat.", "correct": false }, { "text": "The sun is ___ hit.", "correct": false }] },
            { "id": 17, "word": "these", "sentences": [{ "text": "___ are my shoes.", "correct": true }, { "text": "___ this are my shoes.", "correct": false }, { "text": "___ those is my shoes.", "correct": false }] },
            { "id": 18, "word": "clean", "sentences": [{ "text": "___ your room.", "correct": true }, { "text": "___ clear your room.", "correct": false }, { "text": "___ candy your room.", "correct": false }] },
            { "id": 19, "word": "sing", "sentences": [{ "text": "___ a song.", "correct": true }, { "text": "___ song a song.", "correct": false }, { "text": "___ ring a song.", "correct": false }] },
            { "id": 20, "word": "grow", "sentences": [{ "text": "Plants ___.", "correct": true }, { "text": "Plants ___ go.", "correct": false }, { "text": "Plants ___ green.", "correct": false }] },
            { "id": 21, "word": "many", "sentences": [{ "text": "How ___ are there?", "correct": true }, { "text": "How ___ much are there?", "correct": false }, { "text": "How ___ money are there?", "correct": false }] },
            { "id": 22, "word": "together", "sentences": [{ "text": "Play ___.", "correct": true }, { "text": "Play ___ today.", "correct": false }, { "text": "Play ___ to get her.", "correct": false }] },
            { "id": 23, "word": "because", "sentences": [{ "text": "___ it is fun.", "correct": true }, { "text": "___ before it is fun.", "correct": false }, { "text": "___ become it is fun.", "correct": false }] },
            { "id": 24, "word": "shall", "sentences": [{ "text": "We ___ go.", "correct": true }, { "text": "We ___ small go.", "correct": false }, { "text": "We ___ show go.", "correct": false }] },
            { "id": 25, "word": "far", "sentences": [{ "text": "It is very ___.", "correct": true }, { "text": "It is very ___ for.", "correct": false }, { "text": "It is very ___ fast.", "correct": false }] },
            { "id": 26, "word": "laugh", "sentences": [{ "text": "Don't ___.", "correct": true }, { "text": "Don't ___ light.", "correct": false }, { "text": "Don't ___ left.", "correct": false }] },
            { "id": 27, "word": "best", "sentences": [{ "text": "The ___ day.", "correct": true }, { "text": "The ___ better day.", "correct": false }, { "text": "The ___ bust day.", "correct": false }] },
            { "id": 28, "word": "please", "sentences": [{ "text": "Yes, ___.", "correct": true }, { "text": "Yes, ___ play.", "correct": false }, { "text": "Yes, ___ people.", "correct": false }] }
        ]
    }
}; // Don't forget this closing brace!